### ISSUE TITLE
Comments have incorrect highlighting

### ISSUE THREAD

**Issue by batstick** [Thewolfs/cppcolorizationupgrade#1]
When I comment out code, things like strings will still be highlighted. I am running VSCode version 1.40.0 on Linux 4.19 LTS. I can provide more information if needed. Thank you.

![2019-11-18-224302_508x153_scrot](https://user-images.githubusercontent.com/30424137/69114961-045e2c80-0a55-11ea-8883-318bf789b19d.png)

**Comment by batstick** [comment]
I've narrowed it down to the regex in each pattern not accounting for comments. I'm working on a fix for the "entity.name.type.cpp" pattern.

**Comment by InjustFr** [comment]
This repository is no longer maintained as the official Cpp language package has now better colorization tools
